GET http://localhost:4458/

###

POST http://localhost:4458/email HTTP/1.1
content-type: application/json

{
    "name": "Cesar Pereira",
    "phone": "11994875412",
    "cpf": "12598825478",
    "anonimationJustify": "Não desejo mais compartilhar meus dados com o LOJISTA."
}